[package]
name = "rusty-gifts"
version = "0.1.0"
authors = ["Jason Reilly <jdr0887@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[workspace]
members = ["backend", "frontend"]
